package we.are.bubblesort.MovieApp.server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import com.google.appengine.api.utils.SystemProperty;

public final class Database {
		
	private static 	Database 	instance 	= new Database();
	private 		String 		url 		= "";
    private  final 	String 		user 		= "se_user";
    private  final 	String 		pass 		= "SEIsAwesome2015";
    
    private Database(){
    	
    }
    
    /*
     * @returns Database instance of Database
     */
    public static Database getInstance() {
    	return instance;
    }
    
    public Connection getConnection() {
    	Connection conn = null;
    	try {
    		if (SystemProperty.environment.value() == SystemProperty.Environment.Value.Production) {
    			// Connect to Google SQL
    			Class.forName("com.mysql.jdbc.GoogleDriver");
    			url 						= "jdbc:google:mysql://themovieappvnext:themovieappnext/main?user=root";
      		  	conn 						= DriverManager.getConnection(url);
    		} else {
    			// Connecting from an external network.
    			Class.forName("com.mysql.jdbc.Driver");
    			url 						= "jdbc:mysql://80.74.150.210:3306/movieapp";
        		conn 						= DriverManager.getConnection(url, user, pass);
    		}

	    } catch (ClassNotFoundException | SQLException e) {
	      e.printStackTrace();
	    }
    	
    	return conn;
    }
	
	/*
	 * @param sql string used as a command
	 * @returns PreparedStatement
	 */
	public PreparedStatement prepareStatement(String sql) throws SQLException{
		return getConnection().prepareStatement(sql);
	}
	
	/*
	 * @param sql string used as a command
	 * @param auto_generated_keys The given constant tells the driver whether it should make auto-generated keys available for retrieval.
	 * @returns PreparedStatement
	 */
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException{
		return getConnection().prepareStatement(sql, autoGeneratedKeys);
	}
	
}